---
version: 1    
disable_existing_loggers: false
formatters:
    simple:
        datefmt: '%m/%d/%Y %I:%M:%S %p'
        format: '%(asctime)s %(levelname)s %(message)s'
    verbose:
        datefmt: '%m/%d/%Y %I:%M:%S %p'
        format: '%(asctime)s [%(levelname)s] (%(threadName)-10s): %(message)s'
handlers:
    console:
        class: logging.StreamHandler
        formatter: simple
        level: DEBUG
    default:
        backupCount: 15
        class: logging.handlers.RotatingFileHandler
        filename: twitter.log
        formatter: simple
        level: INFO
        maxBytes: 1048576
loggers:
    ? ''
    :   handlers:
        - default
        level: DEBUG
        propagate: true
    eval:
        handlers:
        - console
        level: DEBUG
        propagate: false
    twitter:
        handlers:
        - default
        - console
        level: DEBUG
        propagate: false

